### ISSUE TITLE
Default alias of wc will interfere with wc command on *nix systems

### ISSUE THREAD

**Issue by jcotton42** [EvotecIT/PSWriteColor#1]
The out-of-the-box alias of `wc` for `Write-Color` will interfere with the use of the `wc` (word count) command on Linux/macOS systems. I would suggest removing it, and letting the user set the alias if they want it.

**Comment by PrzemyslawKlys** [comment]
You're right. It will be addressed. You can take a look at PR https://github.com/EvotecIT/PSWriteColor/pull/2 which removes this as well as tackles some other things. It also contains some of the things I've been wondering about for a while. Feel free to leave your opinion! Thanks

**Comment by PrzemyslawKlys** [comment]
Removed alias WC. Published 0.76. I guess I will release next version with changes to psd1 to allow install on Linux by default.
