### ISSUE TITLE
.net core issues when using function on mac

### ISSUE THREAD

**Issue by EricZimmerman** [EvotecIT/PSWriteColor#4]
while i dont have a mac, one of my users does. error looks like this. the script keeps going, but it looks like its trying to index into $Color[] array and cant

![image](https://user-images.githubusercontent.com/4265254/60396296-70271380-9b0d-11e9-86f5-32ee0bcc7f11.png)

**Comment by PrzemyslawKlys** [comment]
Well, I just did a small test

```powershll
Write-Color test,test -Color Red,Yellow
Write-Color test,test2 -Color Red,Yellow,White
Write-Color test,test
```
All works fine. The error on your screen says "Cannot proces the color because -1 is not a valid color". Maybe you're passing Color as variables or something? Alternatively, provide some test case that fails?

**Comment by EricZimmerman** [comment]
Download this script and run it

It exhibits the issue

https://f001.backblazeb2.com/file/EricZimmermanTools/Get-ZimmermanTools.zip

I even had a user add a check that of $defaultcolor is -1 set it to Grey
but same error.

**Comment by PrzemyslawKlys** [comment]
On MacOS 

```powershell
(get-host).ui.rawui  
```

returns -1 for foregroundcolor and for bacckgroundcolor, hence your problem. 

Also why would you need Write-Color if you're using Write-Host all over the place ?:-)

```
Write-Host ""
Write-Host "This script will discover and download all available programs" -BackgroundColor Blue
Write-Host "from https://ericzimmerman.github.io and download them to $Dest" -BackgroundColor Blue
Write-Host "`nA file will also be created in $Dest that tracks the SHA-1 of each file,"
Write-Host "so rerunning the script will only download new versions."
Write-Host "`nTo redownload, remove lines from or delete the CSV file created under $Dest and rerun. Enjoy!`n"
```
Could be replaced with:

```powershell
Write-Color "This script will discover and download all available programs" -BackgroundColor Blue
Write-Color "from https://ericzimmerman.github.io and download them to $Dest" -BackgroundColor Blue -LinesAfter 1
Write-Color  "A file will also be created in $Dest that tracks the SHA-1 of each file,"
Write-Color "so rerunning the script will only download new versions."
Write-Color -LinesBefore 1 -Text "To redownload, remove lines from or delete the CSV file created under $Dest and rerun. Enjoy!" -LinesAfter 1
```

Also it's Gray not Grey, maybe that's why?

**Comment by PrzemyslawKlys** [comment]
Also

```powershell
Write-Host ""
write-color -Text "* ", "Saving downloaded version information to $localDetailsFile" -Color Green,Red
Write-host "`n"
```

Can be replaced with single line:

```powershell
write-color -Text "* ", "Saving downloaded version information to $localDetailsFile" -Color Green,Red -LinesBefore 1 -LinesAfter 1
```

**Comment by EricZimmerman** [comment]
Yes I haven't finished pulling all the old wite-host calls out. I like how
your code allows for color vs write-host as well

**Comment by EricZimmerman** [comment]
As I said I added a check like this after assigning default color

If defaultcolor == -1
defaultcolor = grey

And assuming my end user saved things properly, it didn't fix it

This is why I created the issue because I couldn't see anywhere else it
could have happened from what I've looked at so far.

I may just set defaultcolor to grey and be done with it

**Comment by PrzemyslawKlys** [comment]
```PowerShell
$TestColor = (Get-Host).ui.rawui.ForegroundColor
if ($TestColor -eq -1) {
    $defaultColor = [ConsoleColor]::Gray
} else {
    $defaultColor = $TestColor
}
```

The only thing that comes to my mind is that the user didn't save it properly. The -1 had to come from somewhere and that's the only place I see. The other reason would be that you were trying to save Gray color to $TestColor which was -1 and type of int at that point. You can try above and see if it works.

**Comment by EricZimmerman** [comment]
i found it strange the mac set the colors to -1 at all. i will test out the code and finish porting the write-host calls. thanks for your help and nice function
