### ISSUE TITLE
Doesn't seem to accept parameters when passed

### ISSUE THREAD

**Issue by Doug-Moody** [EvotecIT/PSWriteColor#6]
Great code but may have a personal issue - 

Tried many combinations to get Write-Color to display a $($var)

Typically Write-Host ("Accepts values passed as $($suchhere)") but cannot seem to make this happen here.  The ( )s outside of the "" quotes help display  $($vars) but no combo in our out of quotes like write-color "(" text $($var) ")"   or (" text $($var) ") work.

Help, coffee is running out!

**Comment by PrzemyslawKlys** [comment]
What you’re to display?

**Comment by PrzemyslawKlys** [comment]
```powershell
$suchhere = 'ok'
Write-Host ("Accepts values passed as $($suchhere)")

Write-Host ("Accepts values passed as $($suchhere)")

Write-Color "Accepts values passed as $suchhere"
```

I don't get what you're trying to build?

**Comment by Doug-Moody** [comment]
Hi PrzemyslawKlys
```
    $preCheck = "test"
    Write-Color "   1. ", "Precheck before upgrades. Status: ", "$($preCheck)" -Color Yellow, White, Magenta - NoNewLine; 
```

As a simple example   Passing a string in a variable into what is a line of text.  

Tried it as the above and:

    $preCheck = "test"
    Write-Color ("   1. ", "Precheck before upgrades. Status: ", "$($preCheck)") -Color Yellow, White, Magenta - NoNewLine; 


    $preCheck = "test"
    Write-Color "("   1. ", "Precheck before upgrades. Status: ", "$($preCheck)" ")" -Color Yellow, White, Magenta - NoNewLine; 

Odd, testing again....

**Comment by PrzemyslawKlys** [comment]
What do you want external brackets for? i mean what is the end result?

**Comment by Doug-Moody** [comment]
The Parentheses are being used because that was the only way i could pass them into a regular Write-Host line and was trying to bring it into the Write-Color line.   You mention that you do not need $( )  around a $varible, but I can't seem to get it to accept.   

If it works in your code, I'll continue troubleshooting and we can close this. Always a possible issue on my end as I am working in a very long powershell file.

**Comment by PrzemyslawKlys** [comment]
```powershell
$suchhere = 'ok'
Write-Host ("Accepts values passed as $($suchhere)")

Write-Host ("Accepts values passed as $($suchhere)")

Write-Color "Accepts values passed as $suchhere"
Write-Color "Accepts values passed as $($suchhere)", ' or ', $($suchhere)
```

**Comment by Doug-Moody** [comment]
*** Tested in clean terminal and works as you mentioned. Thanks for the proof & examples!  Will find my issue my main file that is causing this.

**Comment by PrzemyslawKlys** [comment]
Above works. Just need something to work on here... the differenc ebetween write-host and write-color is that write-host takes an object and write-color takes an array of text values.

**Comment by Doug-Moody** [comment]
Status: Closed 
👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻
