### ISSUE TITLE
Transcript with Write-Color

### ISSUE THREAD

**Issue by SupraOva** [EvotecIT/PSWriteColor#9]
Hi,
I'm looking for a way to combine powershell transcript and write-color function. 

In PS console, the result is displayed as expected but passing through the transcript each element between "" inserts a new line of the transcript log (between time and text).

Is there a way around this issue without using the -LogFile parameter?

![firefox_2021-01-22_18-16-21](https://user-images.githubusercontent.com/34113761/105522974-2a78ff80-5cde-11eb-91ef-c90b3be80650.png)

```

> **********************
> Windows PowerShell transcript start
> Start time: 20210122181054
> Username: xxxxxx
> RunAs User: xxxxx
> Configuration Name: 
> Machine: xxxxx
> Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
> Process ID: xxxx
> PSVersion: 5.1.17763.1490
> PSEdition: Desktop
> PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.1490
> BuildVersion: 10.0.17763.1490
> CLRVersion: 4.0.30319.42000
> WSManStackVersion: 3.0
> PSRemotingProtocolVersion: 2.3
> SerializationVersion: 1.1.0.1
> **********************
> [22/01/21 18:10:54]
> Script name : Test-Transcript.ps1
> 
> [22/01/21 18:10:54]
> Sed eveniet neque aut rerum perspiciati
> 
> [22/01/21 18:10:54]
> voluptas est dolorem error et similique
> 
> [22/01/21 18:10:54]
> End script!
> 
> [22/01/21 18:10:54]
> Elapsed Time: 0 hours 0 minutes 0 seconds
> 
> **********************
> Windows PowerShell transcript end
> End time: 20210122181054
> **********************

```
Thanks for your help and your work !

**Comment by PrzemyslawKlys** [comment]
This is by design.  Check similar issue https://github.com/EvotecIT/PSWriteColor/issues/8

There's no work around this limitation. as far as I know.
